name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm update

    - name: Build Tauri App
      run: pnpm run build && pnpm run tauri -- build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: List MSI files
      id: list_files
      run: |
        # 使用 find 命令列出所有需要上传的 .msi 文件，并将结果保存到环境变量文件中
        files=$(find ./src-tauri/target/release/bundle/msi -name '*.msi')
        echo "MSI_FILES=$files" >> $GITHUB_ENV

    - name: Upload MSI files on Windows
      if: runner.os == 'Windows'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for file in ${{ env.MSI_FILES }}; do
          echo "Uploading $file"
          gh release upload ${{ steps.create_release.outputs.upload_url }} "$file" --clobber
        done